language: node_js
node_js:
  - 10
sudo: required
dist: bionic
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install --ignore-scripts
script:
  - npm run test
after_success:
  - echo hello travis