language: node_js
node_js:
  - 10
sudo: required
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install
script:
  - ng test
after_success:
  - echo hello travis