language: node_js
node_js:
  - 10
sudo: required
dist: bionic
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  # To run tests requiring a graphical user interface on Travis CI, use xvfb (X Virtual Framebuffer) to imitate a display
  # Start xvfb and set the right values for the DISPLAY environment variable.
  - xvfb
before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮
install:
  - npm install --ignore-scripts
script:
  - npm run travis:test
after_success:
  - bash ./.travis.sh